[package]
name = "piece-table"
version = "0.1.0"
edition = "2021"

[dependencies]
btep = { version = "0.1.0", path = "../btep" }
append_only_str = { path = "../append_only_str" }
utils = { path = "../utils" }
tokio = { version = "1.42.0", features = ["io-util"] }
futures = "0.3.31"
